        program xcount
        integer icount
        real  a, b, c
         a = 1
         b = 1
         c = 1
         write(6,9002)
9002    format(" "," fibonacci series generated by fortran 77 program")        
        do 100 icount =1,100,1
        c = a + b
        a = b 
        b = c
        write(6,9000) icount, a,b, c
9000    format(" ",i10,f35.0,f35.0,f35.0) 
 100    continue
        end 
        
         










